Game 20 setup socket for chat
KyleDulce/GameSite2 pull request #12
Opened 2022-05-15 16:41 UTC by john-amiscaray

2022-05-15 17:44 UTC, KyleDulce requested changes
Can you add unit tests (Possibly in the Room class) on testing handleGameDataReceived on if a chat message is passed through? You can possible just Mock the SocketController and verify the broadcast message method was called and the regular process is also called

2022-05-15 17:44 UTC, KyleDulce commented on Server/src/main/java/me/dulce/gamesite/gamesite2/rooms/RoomManager.java
> +    public boolean handleIncomingRoomData(User user, GameData data, SocketController controller) {
Couldn't you @autowire the socket controller? RoomManager is a Service here

2022-05-15 17:44 UTC, KyleDulce commented on Server/src/main/java/me/dulce/gamesite/gamesite2/rooms/managers/Room.java
> +    public final boolean handleGameDataReceived(User user, GameData response, SocketController controller){
Socket Controller is a singleton according to its declaration. Would it make more sense to provide it in the constructor?

2022-05-15 18:31 UTC, john-amiscaray commented on Server/src/main/java/me/dulce/gamesite/gamesite2/rooms/RoomManager.java
> +    public boolean handleIncomingRoomData(User user, GameData data, SocketController controller) {
Think that would cause a circular dependency problem

2022-05-15 18:32 UTC, john-amiscaray commented
> Can you add unit tests (Possibly in the Room class) on testing handleGameDataReceived on if a chat message is passed through? You can possible just Mock the SocketController and verify the broadcast message method was called and the regular process is also called

Whoops yeah, I did forget to test. I'll get to that.

2022-05-15 18:39 UTC, KyleDulce commented on Server/src/main/java/me/dulce/gamesite/gamesite2/rooms/RoomManager.java
> +    public boolean handleIncomingRoomData(User user, GameData data, SocketController controller) {
Try lazy injection?
https://www.baeldung.com/circular-dependencies-in-spring section 4.2

2022-05-15 18:40 UTC, john-amiscaray commented on Server/src/main/java/me/dulce/gamesite/gamesite2/rooms/managers/Room.java
> +    public final boolean handleGameDataReceived(User user, GameData response, SocketController controller){
I guess you're right, I could change that

2022-05-18 00:34 UTC, Kevinehh approved these changes

2022-05-20 20:09 UTC, john-amiscaray commented
Pushed a new commit for some refactoring and to address some of your comments. I'll be working on writing the tests now.

2022-05-20 20:51 UTC, john-amiscaray commented
Committed a test for the chat message being broadcasted. I just want to also add tests for the new `SocketMessengerService` class I added. Will do that next commit.

2022-05-21 03:17 UTC, KyleDulce approved these changes
LGTM

2022-05-22 23:22 UTC, merged